# See Serena's documentation for more details on concept of modes:
# https://oraios.github.io/serena/02-usage/050_configuration.html#modes
description: Description of the mode (meta-information only)

# define a prompt which will be included in the system prompt when this mode is activated
# (or will be provided in the project activation message if the mode is activated dynamically).
# See:  https://oraios.github.io/serena/02-usage/050_configuration.html#prompt-templates
prompt: |
  This prompt will form part of the system prompt/initial instructions for agents started in this context.
  Add as much content as needed.
  Leave it undefined if no prompt is needed, i.e.
     prompt: null

# tools to be excluded in this context.
# Find the list of tools here: https://oraios.github.io/serena/01-about/035_tools.html
excluded_tools: []

# included tools that would otherwise be excluded (particularly optional tools that are disabled by default).
# Find the list of tools here: https://oraios.github.io/serena/01-about/035_tools.html
included_optional_tools: []

# fixed set of tools to use as the base tool set (if non-empty), replacing Serena's default set of tools.
# This cannot be combined with non-empty excluded_tools or included_optional_tools.
# Find the list of tools here: https://oraios.github.io/serena/01-about/035_tools.html
fixed_tools: []